using UnityEngine;

public class GO2 : MonoBehaviour
{
    public GameObject Cßpusla;
    bool blanco;
    bool negro;
    void Update()
    {
        var c = Cßpusla.GetComponent<MeshRenderer>().material;
        var SpawnCubo = Instantiate<GameObject>(Cßpusla);

    }

    // Update is called once per frame
    void FixedUpdate()
    {
        if (negro || blanco)
        {
            Debug.Log("La operaciˇn es verdadera, por lo que el color es blanco");
            var c = Cßpusla.GetComponent<MeshRenderer>().material;
            Color colorblanco = c.color = Color.white;
            blanco = false;
        }
        else
        {
            Debug.Log("La operaciˇn es falsa, por lo que el color es negro");
            var c = Cßpusla.GetComponent<MeshRenderer>().material;
            Color colorblanco = c.color = Color.black;
            blanco = true;
        }


    }
}


